version: "3.0"
services:
  redis:
    image: bitnami/redis:latest
    volumes:
      - './persistent/:/bitnami/redis/data'
    environment:
      - REDIS_PORT_NUMBER=7005
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "7005:7005"
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "7002:7002"